local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

supabase:
  service: S3
  access_key_id: <%= ENV['SUPABASE_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['SUPABASE_SECRET_KEY'] %>
  endpoint: <%= ENV['SUPABASE_ENDPOINT'] %>
  bucket: <%= ENV['SUPABASE_BUCKET'] %>
  region: ca-central-1
  force_path_style: true